"""
Django settings for mystock project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1').split(',')

# if DEBUG:
#     ALLOWED_HOSTS = []
# else:
#     ALLOWED_HOSTS = [
#         'mystock.rodriguezalberto.com',
#         'www.mystock.rodriguezalberto.com'
#     ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'inventario',
    'clientes',
    'proveedores',
    'pedidos.apps.PedidosConfig',
    'axes',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'mystock.disable_cache_middleware.DisableClientCacheMiddleware',
]

ROOT_URLCONF = 'mystock.urls'

BASE_DIR_TEMPLATES_GLOBAL = os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR_TEMPLATES_GLOBAL, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mystock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- Configuración de Autenticación ---
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/pedidos/'
LOGOUT_REDIRECT_URL = '/'

# axes configuración

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Número de intentos fallidos
AXES_FAILURE_LIMIT = 5
# Tiempo de espera (horas)
AXES_COOLOFF_TIME = 10
AXES_LOCKOUT_TEMPLATE = 'locked_start.html'
AXES_LOCKOUT_URL = 'locked-start/'

# Tiempo de vida de la sesión en segundos
SESSION_COOKIE_AGE = 7200

# La sesión expira cuando el usuario cierra el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Guarda la sesión en cada request (reinicia el contador de tiempo)
SESSION_SAVE_EVERY_REQUEST = True

# Prevenir acceso a cookies desde JavaScript
SESSION_COOKIE_HTTPONLY = True

# Protección adicional contra ataques CSRF
SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_SECURE = not DEBUG

# Solo usar cookies seguras en producción (cuando DEBUG = False)
SESSION_COOKIE_SECURE = not DEBUG

# configuraciones de seguridad para producción
# if not DEBUG:  # Solo en producción
#     SECURE_SSL_REDIRECT = False
#     SECURE_BROWSER_XSS_FILTER = True
#     SECURE_CONTENT_TYPE_NOSNIFF = True
#     SECURE_HSTS_SECONDS = 31536000
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True
#     SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
#     CSRF_COOKIE_SECURE = True
#     CSRF_COOKIE_SAMESITE = 'Lax'
#     X_FRAME_OPTIONS = 'DENY'
#     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#     CSRF_TRUSTED_ORIGINS = [
#         'https://mystock.rodriguezalberto.com',
#         'https://www.mystock.rodriguezalberto.com'
#     ]

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000 if os.getenv(
        'ENABLE_HSTS', 'False') == 'True' else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
        'ENABLE_HSTS', 'False') == 'True'
    SECURE_HSTS_PRELOAD = os.getenv('ENABLE_HSTS', 'False') == 'True'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'DENY'

    # Solo en producción real con proxy
    if os.getenv('USE_PROXY', 'False') == 'True':
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # CSRF trusted origins desde variable de entorno
    csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
    if csrf_origins:
        CSRF_TRUSTED_ORIGINS = csrf_origins.split(',')

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

# TIME_ZONE = 'UTC' # esta es la opción por defecto

TIME_ZONE = 'Atlantic/Canary'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'pedidos.signals': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
